import { MenuItem } from '@nucleus/fabric';

export const navMainMenuItems = Object.freeze([
  {
    id: 'nucleus-nav-link-libs',
    label: 'Libraries',
    icon: 'icons/outline/code-1.svg',
    iconNgClass: 'outline',
    permission: 'nucleus.libs',
    expanded: true,
    children: [
      {
        id: 'nucleus-nav-link-libs-crud',
        label: 'CRUD',
        icon: 'icons/outline/document-code.svg',
        iconNgClass: 'outline',
        permission: 'nucleus.libs.crud',
        expanded: true,
        children: [
          {
            id: 'nucleus-nav-link-sample-list',
            label: 'Sample list',
            icon: 'icons/outline/grid-1.svg',
            iconNgClass: 'outline',
            routerLink: '/sample/list',
            routerLinkActive: 'active',
            permission: 'nucleus.sample.list',
            active: {
              icon: 'icons/bold/grid-1.svg',
              iconNgClass: 'bold',
            },
          },
        ],
      },
      {
        id: 'nucleus-nav-link-libs-fabric',
        label: 'Fabric',
        icon: 'icons/outline/main-component.svg',
        iconNgClass: 'outline',
        permission: 'nucleus.libs.fabric',
        expanded: true,
        children: [
          {
            id: 'nucleus-nav-link-button',
            label: 'Button',
            // labelNgStyle: { 'background-color': 'red' },
            // labelNgClass: ['nucleus-nav-link'],
            // tooltip: 'Button',
            // tooltipPlacement: 'top',
            icon: 'icons/outline/mouse-square.svg',
            // iconNgStyle: {},
            iconNgClass: 'outline',
            // ngStyle: {},
            // ngClass: ['fab', 'link', 'primary'],
            // disabled: false,
            // hidden: true,
            // href: '',
            routerLink: '/button',
            routerLinkActive: 'active',
            permission: 'nucleus.button',
            active: {
              icon: 'icons/bold/mouse-square.svg',
              iconNgClass: 'bold',
            },
          },
          {
            id: 'nucleus-nav-link-icon',
            label: 'Icon',
            icon: 'icons/outline/shapes.svg',
            iconNgClass: 'outline',
            routerLink: '/icon',
            routerLinkActive: 'active',
            permission: 'nucleus.icon',
            active: {
              icon: 'icons/bold/shapes.svg',
              iconNgClass: 'bold',
            },
          },
          {
            id: 'nucleus-nav-link-menu',
            label: 'Menu',
            icon: 'icons/outline/menu-1.svg',
            iconNgClass: 'outline',
            routerLink: '/menu',
            routerLinkActive: 'active',
            permission: 'nucleus.menu',
            active: {
              icon: 'icons/bold/menu-1.svg',
              iconNgClass: 'bold',
            },
          },
          {
            id: 'nucleus-nav-link-popover',
            label: 'Popover',
            icon: 'icons/outline/message.svg',
            iconNgClass: 'outline',
            routerLink: '/popover',
            routerLinkActive: 'active',
            permission: 'nucleus.popover',
            active: {
              icon: 'icons/bold/message.svg',
              iconNgClass: 'bold',
            },
          },
          {
            id: 'nucleus-nav-link-typography',
            label: 'Typography',
            icon: 'icons/outline/text.svg',
            iconNgClass: 'outline',
            routerLink: '/typography',
            routerLinkActive: 'active',
            permission: 'nucleus.typography',
            active: {
              icon: 'icons/bold/text.svg',
              iconNgClass: 'bold',
            },
          },
        ],
      },
    ],
  },
] as MenuItem[]);
