import { MenuItem } from '@fabric/ui';

export const appMenuItems = Object.freeze([
  {
    id: 'fabric-menu-link-button',
    label: $localize`Button`,
    // labelNgStyle: { 'background-color': 'red' },
    // labelNgClass: ['fabric-menu-link'],
    // tooltip: $localize`Button`,
    // tooltipPlacement: 'top',
    icon: 'icons/outline/tick-circle.svg',
    // iconNgStyle: {},
    iconNgClass: 'outline',
    // ngStyle: {},
    // ngClass: ['ui', 'link', 'primary'],
    // disabled: false,
    // hidden: false,
    // href: '',
    routerLink: '/button',
    routerLinkActive: 'active',
    permission: 'fabric.menu.link.button',
  },
  {
    id: 'fabric-menu-link-icon',
    label: $localize`Icon`,
    icon: 'icons/outline/tick-circle.svg',
    iconNgClass: 'outline',
    routerLink: '/icon',
    routerLinkActive: 'active',
    permission: 'fabric.menu.link.icon',
  },
  {
    id: 'fabric-menu-link-menu',
    label: $localize`Menu`,
    icon: 'icons/bold/tick-circle.svg',
    routerLink: '/menu',
    routerLinkActive: 'active',
    permission: 'fabric.menu.link.menu',
  },
  {
    id: 'fabric-menu-link-typography',
    label: $localize`Typography`,
    icon: 'icons/outline/tick-circle.svg',
    iconNgClass: 'outline',
    permission: 'fabric.menu.link.typography',
    children: [
      {
        id: 'fabric-menu-link-button',
        label: $localize`Button`,
        icon: 'icons/outline/tick-circle.svg',
        iconNgClass: 'outline',
        routerLink: '/button',
        routerLinkActive: 'active',
        permission: 'fabric.menu.link.button',
      },
      {
        id: 'fabric-menu-link-icon',
        label: $localize`Icon`,
        icon: 'icons/outline/tick-circle.svg',
        iconNgClass: 'outline',
        permission: 'fabric.menu.link.icon',
        children: [
          {
            id: 'fabric-menu-link-button',
            label: $localize`Button`,
            icon: 'icons/outline/tick-circle.svg',
            iconNgClass: 'outline',
            routerLink: '/button',
            routerLinkActive: 'active',
            permission: 'fabric.menu.link.button',
          },
          {
            id: 'fabric-menu-link-icon',
            label: $localize`Icon`,
            icon: 'icons/outline/tick-circle.svg',
            iconNgClass: 'outline',
            routerLink: '/icon',
            routerLinkActive: 'active',
            permission: 'fabric.menu.link.icon',
          },
          {
            id: 'fabric-menu-link-menu',
            label: $localize`Menu`,
            icon: 'icons/bold/tick-circle.svg',
            routerLink: '/menu',
            routerLinkActive: 'active',
            permission: 'fabric.menu.link.menu',
          },
          {
            id: 'fabric-menu-link-typography',
            label: $localize`Typography`,
            icon: 'icons/outline/tick-circle.svg',
            iconNgClass: 'outline',
            routerLink: '/typography',
            routerLinkActive: 'active',
            permission: 'fabric.menu.link.typography',
          },
        ],
      },
      {
        id: 'fabric-menu-link-menu',
        label: $localize`Menu`,
        icon: 'icons/bold/tick-circle.svg',
        routerLink: '/menu',
        routerLinkActive: 'active',
        permission: 'fabric.menu.link.menu',
      },
      {
        id: 'fabric-menu-link-typography',
        label: $localize`Typography`,
        icon: 'icons/outline/tick-circle.svg',
        iconNgClass: 'outline',
        routerLink: '/typography',
        routerLinkActive: 'active',
        permission: 'fabric.menu.link.typography',
      },
    ],
  },
] as MenuItem[]);
