export const uiPlacement = [
  'auto',
  'block-auto-corner-auto',
  'block-start-corner-auto',
  'block-start-corner-start',
  'block-start-inline-auto',
  'block-start-inline-start',
  'block-start-edge-start',
  'block-start-inline-center',
  'block-start-edge-end',
  'block-start-inline-end',
  'block-start-corner-end',
  'inline-start-block-auto',
  'inline-start-block-start',
  'inline-start-edge-start',
  'inline-start-block-center',
  'inline-start-edge-end',
  'inline-start-block-end',
  'inline-end-block-auto',
  'inline-end-block-start',
  'inline-end-edge-start',
  'inline-end-block-center',
  'inline-end-edge-end',
  'inline-end-block-end',
  'block-end-corner-auto',
  'block-end-corner-start',
  'block-end-inline-auto',
  'block-end-inline-start',
  'block-end-edge-start',
  'block-end-inline-center',
  'block-end-edge-end',
  'block-end-inline-end',
  'block-end-corner-end',
] as const;
export type UiPlacement = (typeof uiPlacement)[number];
